### ISSUE TITLE
node-hook should be required uncached

### ISSUE THREAD

**Issue by ericmorand-emakina** [ericmorand/stromboli-plugin-twig#104]
Currently, at each render call, the same node-hook instance receive registrations, slowing down the data rendering.

**Comment by ericmorand-emakina** [comment]
`let nh = requireUncached('node-hook');`

**Comment by ericmorand** [comment]
We will go as far as removing node-hook entirely and let subclassers deal with custom require.

**Comment by ericmorand** [comment]
Closed in favor of #105
