### ISSUE TITLE
Handle exceptions thrown by data files

### ISSUE THREAD

**Issue by ericmorand** [ericmorand/stromboli-plugin-twig#16]
Test case:

throw ('Lorem ipsum');

**Comment by ericmorand** [comment]
[local_history.patch.txt](https://github.com/ericmorand/stromboli-plugin-twig/files/615129/local_history.patch.txt)

**Comment by ericmorand** [comment]
`Index: node_modules/stromboli-plugin-twig/src/plugin.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- node_modules/stromboli-plugin-twig/src/plugin.js	(revision )
+++ node_modules/stromboli-plugin-twig/src/plugin.js	(revision )
@@ -86,6 +86,11 @@
                   var binary = template.render(result.data);
 
                   renderResult.addBinary('index.html', binary);
+                },
+                function(result) {
+                  renderResult.addDependency(result.file);
+
+                  return Promise.reject(result.err);
                 }
               );
             }
@@ -111,14 +116,22 @@
 
     return that.exists(dataFile).then(
       function () {
+        result.files.push(dataFile);
+
         delete require.cache[dataFile];
 
-        var data = require(dataFile);
+        try {
+          var data = require(dataFile);
+        }
+        catch (err) {
+          return Promise.reject({
+            err: err,
+            file: dataFile
+          });
+        }
 
         return Promise.resolve(data).then(
           function (data) {
-            result.files.push(dataFile);
-
             if (data.data && data.deps) {
               result.data = data.data;
               result.files = result.files.concat(data.deps);`

**Comment by ericmorand** [comment]
[patch.txt](https://github.com/ericmorand/stromboli-plugin-twig/files/615130/patch.txt)

**Comment by ghost** [comment]
Data file in error should still be returned as a dependency.
